# logging.level.org.springframework.data.mongodb=TRACE
# logging.level.org.springframework.data.mongodb.core.MongoTemplate=TRACE

logging:
  level:
    root: INFO
    org.springframework.data.mongodb: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG


server:
  port: 8084
#  servlet:
#    context-path: /api/portfoio



    
updateBalance: "10 * * * * *"
updateCashFlowStatement: "10 * * * * *"

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: testDatabase