server:
  port: 8084
#  servlet:
#    context-path: /api/portfoio



    
updateBalance: "10 * * * * *"
updateCashFlowStatement: "10 * * * * *"

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: personalFinance