# logging.level.org.springframework.data.mongodb=TRACE
# logging.level.org.springframework.data.mongodb.core.MongoTemplate=TRACE

logging:
  level:
    root: INFO
    org.mongodb.driver.protocol.command: DEBUG



server:
  port: 8084
#  servlet:
#    context-path: /api/portfoio



    
updateBalance: "10 * * * * *"
updateCashFlowStatement: "10 * * * * *"

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: testDatabase
      auto-index-creation: true
  autoconfigure:
    exclude: 'org.springframework.boot.autoconfigure.data.mongo.MongoReactiveDataAutoConfiguration'