# logging.level.org.springframework.data.mongodb=TRACE
# logging.level.org.springframework.data.mongodb.core.MongoTemplate=TRACE

logging:
  level:
    root: INFO
    # org.mongodb.driver.protocol.command: DEBUG


spring:
  data:
    mongodb:
      auto-index-creation: true
